engineStrict: true

allowBuilds:
  'sharp': true
  '@biomejs/biome': false
  '@tailwindcss/oxide': false

patchedDependencies:
  '@material/material-color-utilities': 'patches/@material__material-color-utilities.patch'
