engineStrict: true

dedupePeers: true

allowBuilds:
  '@biomejs/biome': false
  '@tailwindcss/oxide': false

patchedDependencies:
  '@material/material-color-utilities': 'patches/@material__material-color-utilities.patch'

# TODO. Remove this after a day
minimumReleaseAgeExclude:
  - '@sveltejs/kit@2.63.0'
