export const MESSAGES_MODULE_ID = 'i18n:messages'

// To avoid vite dev mode failing module must start with / ./ or ../
export const LOCALE_MODULE_ID = '/@i18n-locale'

export const CONTENT_BANNER = '// Generated by vite-plugin-i18n. Do not edit.\n'
