export const MESSAGES_MODULE_ID = 'i18n:messages'

export const RUNTIME_MODULE_ID = 'i18n:runtime'

export const VIRTUAL_RUNTIME_MODULE_ID = `\0${RUNTIME_MODULE_ID}`

// Virtual module yielding a single locale's compiled messages, served from memory (never
// written to disk) as `/@i18n-locale?locale=<locale>`. One id covers every context a
// locale module is needed in: the dev import-map target (the browser fetches this URL),
// the SSR base-locale import, and the emitted client chunks. It must start with `/`
// because in dev Vite only loads ids that begin with `./` or `/`.
export const LOCALE_MODULE_ID = '/@i18n-locale'

export const CONTENT_BANNER = '// Generated by vite-plugin-i18n. Do not edit.\n\n'
