export const MESSAGES_MODULE_ID = 'i18n:messages'

export const RUNTIME_MODULE_ID = 'i18n:runtime'

export const VIRTUAL_RUNTIME_MODULE_ID = `\0${RUNTIME_MODULE_ID}`

// In dev mode vite can only load paths starting with ./ or /
export const DEV_LOCALE_MODULE_ID = '/@i18n-dev-locale'

export const CONTENT_BANNER = '// Generated by vite-plugin-i18n. Do not edit.\n\n'
