name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 24.5.0
          cache: 'pnpm'

      - run: pnpm install
      - name: Build generated files
        run: pnpm run build
      - run: pnpm run biome-check
      - run: pnpm run prettier-check
      - run: pnpm run check
      - run: pnpm test
